server:
  port: 8080
lavalink:
  server:
    password: "Euonia"
    sources:
      youtube: true
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false
